export const elbaUsers = [
  {
    additionalEmails: [],
    displayName: 'admin 0',
    email: 'admin-0@foo.bar',
    role: 'ADMIN',
    id: '1000',
  },
  {
    additionalEmails: [],
    displayName: 'admin 1',
    email: 'admin-1@foo.bar',
    role: 'ADMIN',
    id: '1001',
  },
  {
    additionalEmails: [],
    displayName: 'admin 2',
    email: 'admin-2@foo.bar',
    role: 'ADMIN',
    id: '1002',
  },
  {
    additionalEmails: [],
    displayName: 'admin 3',
    email: 'admin-3@foo.bar',
    role: 'ADMIN',
    id: '1003',
  },
  {
    additionalEmails: [],
    displayName: 'admin 4',
    email: 'admin-4@foo.bar',
    role: 'ADMIN',
    id: '1004',
  },
  {
    additionalEmails: [],
    displayName: 'member 0',
    email: 'member-0@foo.bar',
    role: 'MEMBER',
    id: '100',
  },
  {
    additionalEmails: [],
    displayName: 'member 1',
    email: 'member-1@foo.bar',
    role: 'MEMBER',
    id: '101',
  },
  {
    additionalEmails: [],
    displayName: 'member 2',
    email: 'member-2@foo.bar',
    role: 'MEMBER',
    id: '102',
  },
  {
    additionalEmails: [],
    displayName: 'member 3',
    email: 'member-3@foo.bar',
    role: 'MEMBER',
    id: '103',
  },
  {
    additionalEmails: [],
    displayName: 'member 4',
    email: 'member-4@foo.bar',
    role: 'MEMBER',
    id: '104',
  },
];
