import type { Metadata } from 'next';
import '@elba-security/design-system/dist/styles.css';

export const metadata: Metadata = {
  title: 'Elba x SharePoint',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
